### ISSUE TITLE
[功能建議] 讓 Android 的 Back 可以關掉 Map 頁時的個別咖啡廳 Bootstrap

### ISSUE THREAD

**Issue by yuchunc** [howtomakeaturn/cafenomad.tw#1]
謝謝你開發的服務！
我幾乎每個禮拜都用得到！

不知道能不能在 Android 裝置下 Map 時的 咖啡廳介紹(Modal) 可以用 Back 關閉?

目前沒有這個功能 所以會造成退回到之前的頁面 然後關閉 Modal 的小 X 在右上角 有時候不好找也不太直覺

**Comment by howtomakeaturn** [comment]
謝謝你的回報
不好意思 遲至今日才 solve 這個 issue
我終於找到 solution 處理它了
應該可以了 你再試試看唷
